///////////////////////////////////////////////////////////
//  Branch.cs
//  Implementation of the Class Branch
//  Generated by Enterprise Architect
//  Created on:      30-Nov-2023 11:11:02 AM
//  Original author: mohda
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OOD_Project
{
    public class Branch
    {

        private int branchId;
        private string branchName;
        private string phoneNumber;

        public Branch(int branchId, string branchName, string phoneNumber)
        {
            this.branchId = branchId;
            this.BranchName = branchName;
            this.phoneNumber = phoneNumber;
        }

        ~Branch()
        {

        }


        public int BranchId
        {
            get
            {
                return branchId;
            }
            set
            {
                branchId = value;
            }
        }



        public string PhoneNumber
        {
            get
            {
                return phoneNumber;
            }
            set
            {
                phoneNumber = value;
            }
        }

        public string BranchName { get => branchName; set => branchName = value; }

    }//end Branch
}

