///////////////////////////////////////////////////////////
//  Branch.cs
//  Implementation of the Class Branch
//  Generated by Enterprise Architect
//  Created on:      30-Nov-2023 11:11:02 AM
//  Original author: mohda
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OOD_Project
{
    public class Branch
    {

        private string area;
        private int branchId;
        private string city;
        private string name;
        private string phoneNumber;
        private Department department;

        public Branch(string area, int branchId, string city, string name, string phoneNumber)
        {
            this.area = area;
            this.branchId = branchId;
            this.city = city;
            this.name = name;
            this.phoneNumber = phoneNumber;
        }

        ~Branch()
        {

        }

        public string Area
        {
            get
            {
                return area;
            }
            set
            {
                area = value;
            }
        }

        public int BranchId
        {
            get
            {
                return branchId;
            }
            set
            {
                branchId = value;
            }
        }

        public string City
        {
            get
            {
                return city;
            }
            set
            {
                city = value;
            }
        }

        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }

        public string PhoneNumber
        {
            get
            {
                return phoneNumber;
            }
            set
            {
                phoneNumber = value;
            }
        }

        public Department Department { get => department; set => department = value; }
    }//end Branch
}

