///////////////////////////////////////////////////////////
//  Class.cs
//  Implementation of the Class Class
//  Generated by Enterprise Architect
//  Created on:      30-Nov-2023 11:07:25 AM
//  Original author: mohda
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows.Forms;


namespace OOD_Project
{
    public enum WeekDays
    {
        saturday,
        sunday,
        monday,
        tuesday,
        wednesday,
        thursday,
        friday
    }


    public class Class
    {

        private int classId;
        private string building;
        private string roomNumber;
        private WeekDays dayOfTheWeek;
        private DateTime endTime;
        private DateTime startTime;
        private Section section;

        public Class(int classId, string building, string roomNumber, WeekDays dayOfTheWeek, DateTime endTime, DateTime startTime, Section section)
        {
            this.classId = classId;
            this.building = building;
            this.roomNumber = roomNumber;
            this.dayOfTheWeek = dayOfTheWeek;
            this.endTime = endTime;
            this.startTime = startTime;
            this.section = section;
        }



        public static void AddClass(Class c)
        {
            DatabaseManager dbm = DatabaseManager.Instance();
            dbm.Connection.Open();
            dbm.Command = dbm.Connection.CreateCommand();

            dbm.Command.Parameters.AddWithValue("@start_time", c.StartTime);
            dbm.Command.Parameters.AddWithValue("@end_time", c.EndTime);
            dbm.Command.Parameters.AddWithValue("@building", c.Building);
            dbm.Command.Parameters.AddWithValue("@room_number", c.RoomNumber);
            dbm.Command.Parameters.AddWithValue("@section_id", c.Section.Id);
            dbm.Command.Parameters.AddWithValue("@week_day_id", (int)c.DayOfTheWeek+1);
            dbm.Command.CommandText = "INSERT INTO [dbo].[class] (class_id, start_time, end_time, building, room_number, section_id, week_day_id)" +
                "VALUES (NEXT VALUE FOR [dbo].[classIDSequence], @start_time, @end_time, @building, @room_number, @section_id, @week_day_id)";

            try
            {
                dbm.Command.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
            finally
            {
                dbm.Command.Parameters.Clear();
                dbm.Connection.Close();
            }
        }

        public string Building
        {
            get
            {
                return building;
            }
            set
            {
                building = value;
            }
        }

        public int ClassId
        {
            get
            {
                return classId;
            }
            set
            {
                classId = value;
            }
        }

        public DateTime EndTime
        {
            get
            {
                return endTime;
            }
            set
            {
                endTime = value;
            }
        }

        public string RoomNumber
        {
            get
            {
                return roomNumber;
            }
            set
            {
                roomNumber = value;
            }
        }

        public DateTime StartTime
        {
            get
            {
                return startTime;
            }
            set
            {
                startTime = value;
            }
        }

        public WeekDays DayOfTheWeek { get => dayOfTheWeek; set => dayOfTheWeek = value; }
        public Section Section { get => section; set => section = value; }
    }//end Class
}