///////////////////////////////////////////////////////////
//  Department.cs
//  Implementation of the Class Department
//  Generated by Enterprise Architect
//  Created on:      30-Nov-2023 11:10:57 AM
//  Original author: mohda
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace OOD_Project
{
    public class Department
    {

        private string buildingName;
        private int deptId;
        private string deptName;
        private string phoneNumber;
        public Teacher m_Teacher;

        public Department()
        {

        }

        ~Department()
        {

        }

        public string BuildingName
        {
            get
            {
                return buildingName;
            }
            set
            {
                BuildingName = value;
            }
        }

        public int DeptId
        {
            get
            {
                return deptId;
            }
            set
            {
                deptId = value;
            }
        }

        public string DeptName
        {
            get
            {
                return deptName;
            }
            set
            {
                deptName = value;
            }
        }

        public string PhoneNumber
        {
            get
            {
                return phoneNumber;
            }
            set
            {
                phoneNumber = value;
            }
        }

    }//end Department
}
